// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDyUhf4s4MQw3mDUxGyW2VA6fq50Ql_wI',
    appId: '1:911112448037:web:d328ab85d2627e8c8937cc',
    messagingSenderId: '911112448037',
    projectId: 'baakas-197b9',
    authDomain: 'baakas-197b9.firebaseapp.com',
    storageBucket: 'baakas-197b9.firebasestorage.app',
    measurementId: 'G-LE23054Z6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0d_PDGTm3dr3fJU328WmQGf79z9C2zWw',
    appId: '1:911112448037:android:22569abb13dcda3a8937cc',
    messagingSenderId: '911112448037',
    projectId: 'baakas-197b9',
    storageBucket: 'baakas-197b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6EubIa31tXF-hNkGj9Gul5mUzUu61xeU',
    appId: '1:911112448037:ios:5efc5f89f57c3ea48937cc',
    messagingSenderId: '911112448037',
    projectId: 'baakas-197b9',
    storageBucket: 'baakas-197b9.firebasestorage.app',
    iosClientId:
        '911112448037-5nc9446ghus7ohe96b2q5sb8aftn6ktj.apps.googleusercontent.com',
    iosBundleId: 'com.example.baakas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY_97c_ig6ijCy9Vp7D5NHwIVPVk8NA7Y',
    appId: '1:338034973026:ios:7ea9470d956afc9b6fb43b',
    messagingSenderId: '338034973026',
    projectId: 'baakas-197b9',
    storageBucket: 'baakas-197b9.firebasestorage.app',
    androidClientId:
        '338034973026-5ki721adq1ni3r2vi7r27gjv45l7r9mf.apps.googleusercontent.com',
    iosClientId:
        '338034973026-0cqchcf07je61tuovm7eu45aod5a0pum.apps.googleusercontent.com',
    iosBundleId: 'com.example.baakas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmp1RM9H6HXw378PkcpijMPt1GEcblzX4',
    appId: '1:338034973026:web:f0eee54b40abf49b6fb43b',
    messagingSenderId: '338034973026',
    projectId: 'baakas-197b9',
    authDomain: 'baakas-197b9.firebaseapp.com',
    storageBucket: 'baakas-197b9.firebasestorage.app',
    measurementId: 'G-N7916ND3WZ',
  );
}
